server:
  port: 8080
  servlet:
    context-path: /app

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: biz-1
    prefer-ip-address: true