server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
  instance:
    instance-id: zuul-1
    prefer-ip-address: true

zuul:
  routes:
    mypower:
      serviceId: server-biz
      path: /biz1/**
  ignored-services: server-biz # 禁用单个服务，不能通过服务名字访问，禁用所有 “*”
  prefix: /api  #配置访问前缀
  #strip-prefix: false #